local Beams, super = Class(Wave)


function Beams:init()
    super.init(self)
    self.time = 15
end

function Beams:onStart()
    Assets.playSound("appear_choppy")
    local arena = Game.battle.arena
    local soul = Game.battle.soul
    local spawn = function(x,y)
        local angle = math.rad(180)
        self.timer:after(0.6, function()
        local angle = MathUtils.angle(x, y, soul.x, soul.y)
        local bullet = self:spawnBullet("beam", x, y, angle, 0)
        bullet.remove_offscreen = false
        bullet.scale_y = 0
        Assets.stopAndPlaySound("scytheburst")
        self.timer:tween(0.5, bullet, {scale_y=2},"in-sine", function()
        self.timer:after(0.5, function()
        self.timer:tween(0.5, bullet, {scale_y=0},"in-sine", function()
        bullet:remove()
        end)
        end)
        end)
    end)
end
    Assets.playSound("ghostappear", 1, 0.8)
    self.timer:script(function(wait)
        self.timer:tween(0.5, arena, {width=180,height=180}, "out-sine")
        wait(0.6)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
        spawn(SCREEN_WIDTH + 80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(-80,MathUtils.random(arena.top, arena.bottom))
        wait(0.1)
        spawn(MathUtils.random(arena.left, arena.right),SCREEN_HEIGHT + 80)
        wait(0.1)
        spawn(MathUtils.random(arena.right, arena.left),0 - 80)
        wait(1)
    end)
end

return Beams